const TRADE_COMMANDS = {
  OPEN_LONG: 'OPEN_LONG',
  OPEN_SHORT: 'OPEN_SHORT',
  LONG_TP_1: 'LONG_TP_1',
  LONG_TP_2: 'LONG_TP_2',
  LONG_TP_3: 'LONG_TP_3',
  LONG_TP_4: 'LONG_TP_4',
  SHORT_TP_1: 'SHORT_TP_1',
  SHORT_TP_2: 'SHORT_TP_2',
  SHORT_TP_3: 'SHORT_TP_3',
  SHORT_TP_4: 'SHORT_TP_4',
  CLOSE_LONG: 'CLOSE_LONG',
  CLOSE_SHORT: 'CLOSE_SHORT'
};

module.exports = { TRADE_COMMANDS }; 